version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/turbulence
      - JWT_SECRET=prod_secret_key
      - PYTHON_API_URL=http://python-service:8000
    depends_on:
      - mongodb

  python-service:
    build: ./python-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - python-service
